

ORIGINAL_COLORS_LIST = [
    '#ff0000',
    '#ff5000',
    '#ffe100',
    '#fff100',
    '#bbff00',
    '#6bff00',
    '#1aff00',
    '#00ff35',
    '#00ff86',
    '#00ffd6',
    '#00d6ff',
    '#0086ff',
    '#0035ff',
    '#1a00ff',
    '#6b00ff',
    '#bb00ff',
    '#ff00f1',
    '#ff00a1',
    '#ff0050',
    '#ff0000',
]
LIGHTER_COLORS_LIST = [
    '#ff0000',
    '#ff5000',
    '#ffe100',
    '#fff100',
    '#bbff00',
    '#6bff00',
    '#1aff00',
    '#00ff35',
    '#00ff85',
    '#00ffd6',
    '#00d5ff',
    '#0085ff',
    '#0035ff',
    '#1900ff',
    '#6b00ff',
    '#bb00ff',
    '#ff00f1',
    '#ff00a0',
    '#ff0050',
    '#ff0000',
]
DARKER_COLORS_LIST = [
    '#7f0000',
    '#7f2800',
    '#7f5000',
    '#7f7800',
    '#5d7f00',
    '#357f00',
    '#0d7f00',
    '#007f1a',
    '#007f42',
    '#007f6b',
    '#006a7f',
    '#00427f',
    '#001a7f',
    '#0c007f',
    '#35007f',
    '#5d007f',
    '#7f0078',
    '#7f0050',
    '#7f0028',
    '#7f0000',
]


# TECH_COLORS_DICT = {'Digital communication': '#ffe100',
#                     'Telecommunications': '#ffe100',
#                     'Computer technology': '#ffe100',
#                     'Audio-visual technology': '#ffe100',
#                     'IT methods for management': '#ffe100',
#                     'Pharmaceuticals': '#ff0000',
#                     'Organic fine chemistry': '#ff0000',
#                     'Basic communication processes': '#ffe100',
#                     'Optics': '#1aff00',
#                     'Semiconductors': '#ffe100',
#                     'Biotechnology': '#1aff00',
#                     'Medical technology': '#ffe100',
#                     'Micro-structural and nano-technology': '#ff0000',
#                     'Measurement': '#1aff00',
#                     'Food chemistry': '#ff0000',
#                     'Control': '#1aff00',
#                     'Furniture, games': 'gray',
#                     'Basic materials chemistry': '#ff0000',
#                     'Chemical engineering': '#ff0000',
#                     'Environmental technology': '#ff0000',
#                     'Macromolecular chemistry, polymers': '#ff0000',
#                     'Engines, pumps, turbines': '#0035ff',
#                     'Electrical machinery, apparatus, energy': '#ffe100',
#                     'Textile and paper machines': '#0035ff',
#                     'Other consumer goods': 'gray',
#                     'Civil engineering': 'gray',
#                     'Materials, metallurgy': '#ff0000',
#                     'Other special machines': '#0035ff',
#                     'Thermal processes and apparatus': '#0035ff',
#                     'Surface technology, coating': '#ff0000',
#                     'Transport': '#0035ff',
#                     'Handling': '#0035ff',
#                     'Mechanical elements': '#0035ff',
#                     'Machine tools': '#0035ff',
#                     'Analysis of biological materials': '#1aff00'}

TECH_COLORS_DICT = {'Digital communication': 'tab:blue',
                    'Telecommunications': 'tab:blue',
                    'Computer technology': 'tab:blue',
                    'Audio-visual technology': 'tab:blue',
                    'IT methods for management': 'tab:blue',
                    'Pharmaceuticals': 'tab:red',
                    'Organic fine chemistry': 'tab:red',
                    'Basic communication processes': 'tab:blue',
                    'Optics': 'tab:green',
                    'Semiconductors': 'tab:blue',
                    'Biotechnology': 'tab:green',
                    'Medical technology': 'tab:blue',
                    'Micro-structural and nano-technology': 'tab:red',
                    'Measurement': 'tab:green',
                    'Food chemistry': 'tab:red',
                    'Control': 'tab:green',
                    'Furniture, games': 'tab:gray',
                    'Basic materials chemistry': 'tab:red',
                    'Chemical engineering': 'tab:red',
                    'Environmental technology': 'tab:red',
                    'Macromolecular chemistry, polymers': 'tab:red',
                    'Engines, pumps, turbines': '#ffe100',
                    'Electrical machinery, apparatus, energy': 'tab:blue',
                    'Textile and paper machines': '#ffe100',
                    'Other consumer goods': 'tab:gray',
                    'Civil engineering': 'tab:gray',
                    'Materials, metallurgy': 'tab:red',
                    'Other special machines': '#ffe100',
                    'Thermal processes and apparatus': '#ffe100',
                    'Surface technology, coating': 'tab:red',
                    'Transport': '#ffe100',
                    'Handling': '#ffe100',
                    'Mechanical elements': '#ffe100',
                    'Machine tools': '#ffe100',
                    'Analysis of biological materials': 'tab:green'}